<?php
$title = 'Authors';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('author', ['action' => 'add']) ?>">Add new author</a>
</p>
<?php if(!isset($paginator)):?>
<div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">Close</span>
  </button>
  An error occurred while getting Authors.
</div>
<?php else: ?>
<table class="table">
    <tr>
        <th>ID</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Date of birth</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($paginator as $author):?>
    <tr>
        <td><?php echo $this->escapeHtml($author->entity_id);?></td>
        <td><?php echo $this->escapeHtml($author->first_name);?></td>
        <td><?php echo $this->escapeHtml($author->last_name);?></td>
        <td><?php echo $this->escapeHtml($author->dob);?></td>
        <td>
            <a href="<?php echo $this->url(
                    'author',[
                        'action'=>'view',
                        'id'=>$author->entity_id,
                    ]
                    );?>">View
            </a>
            <a href="<?php echo $this->url(
                    'author',[
                        'action'=>'edit',
                        'id'=>$author->entity_id,
                    ]
                    );?>">Edit
            </a>
            <a href="<?php echo $this->url(
                    'author',[
                        'action'=>'delete',
                        'id'=>$author->entity_id,
                    ]
                    );?>">Delete
            </a>
        </td>
    </tr>
    <?php endforeach;?>
</table>
<?php endif;?>

<?php echo $this->paginationControl(
        $this->paginator,
        'sliding',
        'partial/paginator',
        ['route'=>'author']
        );?>